-- Find all tables with the same name between RDB and RDB_MODERN databases
SELECT 
    t1.TABLE_NAME,
    t1.TABLE_SCHEMA as [Schema_RDB],
    t2.TABLE_SCHEMA as [Schema_RDB_MODERN]
FROM 
    RDB.INFORMATION_SCHEMA.TABLES t1
INNER JOIN 
    RDB_MODERN.INFORMATION_SCHEMA.TABLES t2
ON 
    t1.TABLE_NAME = t2.TABLE_NAME
WHERE 
    t1.TABLE_TYPE = 'BASE TABLE'
    AND t2.TABLE_TYPE = 'BASE TABLE'
ORDER BY 
    t1.TABLE_NAME;
