-- Find all tables from matching_rdb_tables that do NOT have at least one "UID" column
-- Returns the table name and its corresponding "_KEY" columns

-- RDB Database
SELECT
    t.TABLE_NAME,
    STRING_AGG(c.COLUMN_NAME, ', ') AS KEY_COLUMNS
FROM 
    RDB.INFORMATION_SCHEMA.TABLES t
LEFT JOIN
    RDB.INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME
    AND c.COLUMN_NAME LIKE '%KEY%'
WHERE 
    t.TABLE_NAME IN (
        'ACTIVITY_LOG_DETAIL', 'ACTIVITY_LOG_MASTER', 'ACTIVITY_LOG_MASTER_LAST_SAS', 'ACTIVITY_STATUS',
        'AGGREGATE_REPORT_DATAMART', 'ANTIMICROBIAL', 'ANTIMICROBIAL_GROUP', 'BMIRD_CASE',
        'BMIRD_MULTI_VALUE_FIELD', 'BMIRD_MULTI_VALUE_FIELD_GROUP', 'BMIRD_STREP_PNEUMO_DATAMART', 'CASE_COUNT',
        'CASE_LAB_DATAMART', 'CODE_VAL_GENERAL', 'CODESET', 'CONDITION', 'CONFIRMATION_METHOD',
        'CONFIRMATION_METHOD_GROUP', 'COVID_CASE_DATAMART', 'COVID_LAB_DATAMART', 'COVID_VACCINATION_DATAMART',
        'CRS_CASE', 'D_ADDL_RISK', 'D_ADDL_RISK_GROUP', 'D_CASE_MANAGEMENT', 'D_CONTACT_RECORD',
        'D_DISEASE_SITE', 'D_DISEASE_SITE_GROUP', 'D_GT_12_REAS', 'D_GT_12_REAS_GROUP',
        'D_HC_PROV_TY_3', 'D_HC_PROV_TY_3_GROUP', 'D_INTERVIEW', 'D_INTERVIEW_NOTE',
        'D_INV_ADMINISTRATIVE', 'D_INV_CLINICAL', 'D_INV_COMPLICATION', 'D_INV_CONTACT',
        'D_INV_DEATH', 'D_INV_EPIDEMIOLOGY', 'D_INV_HIV', 'D_INV_ISOLATE_TRACKING',
        'D_INV_LAB_FINDING', 'D_INV_MEDICAL_HISTORY', 'D_INV_MOTHER', 'D_INV_OTHER',
        'D_INV_PATIENT_OBS', 'D_INV_PLACE_REPEAT', 'D_INV_PREGNANCY_BIRTH', 'D_INV_RESIDENCY',
        'D_INV_RISK_FACTOR', 'D_INV_SOCIAL_HISTORY', 'D_INV_SYMPTOM', 'D_INV_TRAVEL',
        'D_INV_TREATMENT', 'D_INV_UNDER_CONDITION', 'D_INV_VACCINATION', 'D_INVESTIGATION_REPEAT',
        'D_INVESTIGATION_REPEAT_INC', 'D_LDF_META_DATA', 'D_MOVE_CNTRY', 'D_MOVE_CNTRY_GROUP',
        'D_MOVE_CNTY', 'D_MOVE_CNTY_GROUP', 'D_MOVE_STATE', 'D_MOVE_STATE_GROUP',
        'D_MOVED_WHERE', 'D_MOVED_WHERE_GROUP', 'D_ORGANIZATION', 'D_OUT_OF_CNTRY',
        'D_OUT_OF_CNTRY_GROUP', 'D_PATIENT', 'D_PCR_SOURCE', 'D_PCR_SOURCE_GROUP',
        'D_PLACE', 'D_PROVIDER', 'D_RASH_LOC_GEN', 'D_RASH_LOC_GEN_GROUP',
        'D_SMR_EXAM_TY', 'D_SMR_EXAM_TY_GROUP', 'D_TB_HIV', 'D_TB_PAM',
        'D_VACCINATION', 'D_VAR_PAM', 'DATA_VALIDATION', 'DATA_VALIDATION_MESSAGE',
        'DATAMART_REFRESH_ACTIVITY_LOG', 'DIMENSION_KEYS_PAGECASEID', 'DIMENSIONAL_KEYS', 'DM_INV_ARBO_HUMAN',
        'DM_INV_C_AURIS', 'DM_INV_CONG_SYPHILIS', 'DM_INV_CP_CRE', 'DM_INV_GENERIC_V2',
        'DM_INV_HEPATITIS_A_ACUTE', 'DM_INV_HEPATITIS_B_C_ACUTE', 'DM_INV_HEPATITIS_B_C_CHRONIC', 'DM_INV_HEPATITIS_B_PERINATAL',
        'DM_INV_HEPATITIS_CORE', 'DM_INV_HIV', 'DM_INV_MIS_COVID_19', 'DM_INV_STD',
        'DQ_ALL_CASE', 'ENTITY_KEYSTORE_INC', 'ENTITY_KEYSTORE_STD', 'ETL_DQ_LOG',
        'ETL_HEALTH_CHECK_PAT_DATA', 'ETL_MISSING_PATIENT', 'ETL_MISSING_RECORD', 'ETL_PROCESS',
        'EVENT_METRIC', 'EVENT_METRIC_INC', 'F_CONTACT_RECORD_CASE', 'F_INTERVIEW_CASE',
        'F_PAGE_CASE', 'F_PAGE_CASE_TEMP_INC', 'F_S_INV_CASE', 'F_S_STD_HIV_CASE',
        'F_S_TB_PAM', 'F_S_VAR_PAM', 'F_STD_PAGE_CASE', 'F_STD_PAGE_CASE_TEMP_INC',
        'F_TB_PAM', 'F_VACCINATION', 'F_VAR_PAM', 'GENERIC_CASE',
        'GEOCODING_LOCATION', 'HEP100', 'HEP_MULTI_VALUE_FIELD', 'HEP_MULTI_VALUE_FIELD_GROUP',
        'HEPATITIS_CASE', 'HEPATITIS_DATAMART', 'INIT', 'INV_HIV',
        'INV_SUMM_DATAMART', 'INVESTIGATION', 'job_batch_log', 'job_flow_log',
        'L_ADDL_RISK', 'L_CONFIRMATION_METHOD', 'L_CONTACT_RECORD', 'L_DISEASE_SITE',
        'L_GT_12_REAS', 'L_HC_PROV_TY_3', 'L_INTERVIEW', 'L_INTERVIEW_NOTE',
        'L_INV_ADMINISTRATIVE', 'L_INV_ADMINISTRATIVE_INC', 'L_INV_CLINICAL', 'L_INV_CLINICAL_INC',
        'L_INV_COMPLICATION', 'L_INV_COMPLICATION_INC', 'L_INV_CONTACT', 'L_INV_CONTACT_INC',
        'L_INV_DEATH', 'L_INV_DEATH_INC', 'L_INV_EPIDEMIOLOGY', 'L_INV_EPIDEMIOLOGY_INC',
        'L_INV_HIV', 'L_INV_HIV_INC', 'L_INV_ISOLATE_TRACKING', 'L_INV_ISOLATE_TRACKING_INC',
        'L_INV_LAB_FINDING', 'L_INV_LAB_FINDING_INC', 'L_INV_MEDICAL_HISTORY', 'L_INV_MEDICAL_HISTORY_INC',
        'L_INV_MOTHER', 'L_INV_MOTHER_INC', 'L_INV_OTHER', 'L_INV_OTHER_INC',
        'L_INV_PATIENT_OBS', 'L_INV_PATIENT_OBS_INC', 'L_INV_PLACE_REPEAT', 'L_INV_PREGNANCY_BIRTH',
        'L_INV_PREGNANCY_BIRTH_INC', 'L_INV_RESIDENCY', 'L_INV_RESIDENCY_INC', 'L_INV_RISK_FACTOR',
        'L_INV_RISK_FACTOR_INC', 'L_INV_SOCIAL_HISTORY', 'L_INV_SOCIAL_HISTORY_INC', 'L_INV_SYMPTOM',
        'L_INV_SYMPTOM_INC', 'L_INV_TRAVEL', 'L_INV_TRAVEL_INC', 'L_INV_TREATMENT',
        'L_INV_TREATMENT_INC', 'L_INV_UNDER_CONDITION', 'L_INV_UNDER_CONDITION_INC', 'L_INV_VACCINATION',
        'L_INV_VACCINATION_INC', 'L_INVESTIGATION', 'L_INVESTIGATION_REPEAT', 'L_INVESTIGATION_REPEAT_INC',
        'L_LAB_TEST', 'L_MOVE_CNTRY', 'L_MOVE_CNTY', 'L_MOVE_STATE',
        'L_MOVED_WHERE', 'L_OBSERVATION_MAP', 'L_ORGANIZATION', 'L_OUT_OF_CNTRY',
        'L_PATIENT', 'L_PCR_SOURCE', 'L_PLACE', 'L_PROVIDER',
        'L_RASH_LOC_GEN', 'L_SMR_EXAM_TY', 'L_TB_HIV', 'L_TB_PAM',
        'L_VACCINATION', 'L_VAR_PAM', 'LAB100', 'LAB101',
        'LAB_RESULT_COMMENT', 'LAB_RESULT_CONDITION', 'LAB_RESULT_GROUP', 'LAB_RESULT_VAL',
        'LAB_RESULT_VAL_LARGE_TXT', 'LAB_RPT_USER_COMMENT', 'LAB_TEST', 'LAB_TEST_RESULT',
        'LDF_BMIRD', 'LDF_DATA', 'LDF_DATAMART_COLUMN_REF', 'LDF_DATAMART_TABLE_REF',
        'LDF_FOORNE', 'LDF_GENERIC', 'LDF_GENERIC1', 'LDF_GENERIC2',
        'LDF_GROUP', 'LDF_HEPATITIS', 'LDF_MUMPS', 'LDF_TETANUS',
        'LDF_VACCINE_PREVENT_DISEASES', 'LOOKUP_TABLE_N_INV_ADMINISTRATIVE', 'LOOKUP_TABLE_N_INV_CLINICAL', 'LOOKUP_TABLE_N_INV_COMPLICATION',
        'LOOKUP_TABLE_N_INV_CONTACT', 'LOOKUP_TABLE_N_INV_DEATH', 'LOOKUP_TABLE_N_INV_EPIDEMIOLOGY', 'LOOKUP_TABLE_N_INV_HIV',
        'LOOKUP_TABLE_N_INV_ISOLATE_TRACKING', 'LOOKUP_TABLE_N_INV_LAB_FINDING', 'LOOKUP_TABLE_N_INV_MEDICAL_HISTORY', 'LOOKUP_TABLE_N_INV_MOTHER',
        'LOOKUP_TABLE_N_INV_OTHER', 'LOOKUP_TABLE_N_INV_PATIENT_OBS', 'LOOKUP_TABLE_N_INV_PREGNANCY_BIRTH', 'LOOKUP_TABLE_N_INV_RESIDENCY',
        'LOOKUP_TABLE_N_INV_RISK_FACTOR', 'LOOKUP_TABLE_N_INV_SOCIAL_HISTORY', 'LOOKUP_TABLE_N_INV_SYMPTOM', 'LOOKUP_TABLE_N_INV_TRAVEL',
        'LOOKUP_TABLE_N_INV_TREATMENT', 'LOOKUP_TABLE_N_INV_UNDER_CONDITION', 'LOOKUP_TABLE_N_INV_VACCINATION', 'LOOKUP_TABLE_N_REPT',
        'MEASLES_CASE', 'MISSING_LAB_CASES', 'MORB_RPT_USER_COMMENT', 'MORBIDITY_REPORT',
        'MORBIDITY_REPORT_DATAMART', 'MORBIDITY_REPORT_EVENT', 'NBS_CASE_ANSWER_REPT', 'NBS_PAGE',
        'NOTIFICATION', 'NOTIFICATION_EVENT', 'ORGANIZATION_LDF_GROUP', 'PAGE_DATE_TABLE_REPT',
        'PATIENT_LDF_GROUP', 'PERTUSSIS_CASE', 'PERTUSSIS_SUSPECTED_SOURCE_FLD', 'PERTUSSIS_SUSPECTED_SOURCE_GRP',
        'PERTUSSIS_TREATMENT_FIELD', 'PERTUSSIS_TREATMENT_GROUP', 'PHC_CASE_UIDS', 'PHC_CASE_UIDS_ALL',
        'Phc_keys', 'PHC_UIDS', 'PHC_UIDS_ALL', 'phc_uids_REPT',
        'PROVIDER_LDF_GROUP', 'RDB_DATE', 'RDB_TABLE_METADATA', 'RDB_UI_METADATA_REPT',
        'rdb_ui_metadata_rept_temp', 'REF_FORMCODE_TRANSLATION', 'RESULT_COMMENT_GROUP', 'RUBELLA_CASE',
        'S_ADDL_RISK', 'S_CONFIRMATION_METHOD_GROUP', 'S_CONTACT_RECORD', 'S_DISEASE_SITE',
        'S_GT_12_REAS', 'S_HC_PROV_TY_3', 'S_INTERVIEW', 'S_INTERVIEW_NOTE',
        'S_INV_ADMINISTRATIVE', 'S_INV_ADMINISTRATIVE_INC', 'S_INV_CLINICAL', 'S_INV_CLINICAL_INC',
        'S_INV_COMPLICATION', 'S_INV_COMPLICATION_INC', 'S_INV_CONTACT', 'S_INV_CONTACT_INC',
        'S_INV_DEATH', 'S_INV_DEATH_INC', 'S_INV_EPIDEMIOLOGY', 'S_INV_EPIDEMIOLOGY_INC',
        'S_INV_HIV', 'S_INV_HIV_INC', 'S_INV_ISOLATE_TRACKING', 'S_INV_ISOLATE_TRACKING_INC',
        'S_INV_LAB_FINDING', 'S_INV_LAB_FINDING_INC', 'S_INV_MEDICAL_HISTORY', 'S_INV_MEDICAL_HISTORY_INC',
        'S_INV_MOTHER', 'S_INV_MOTHER_INC', 'S_INV_OTHER', 'S_INV_OTHER_INC',
        'S_INV_PATIENT_OBS', 'S_INV_PATIENT_OBS_INC', 'S_INV_PREGNANCY_BIRTH', 'S_INV_PREGNANCY_BIRTH_INC',
        'S_INV_RESIDENCY', 'S_INV_RESIDENCY_INC', 'S_INV_RISK_FACTOR', 'S_INV_RISK_FACTOR_INC',
        'S_INV_SOCIAL_HISTORY', 'S_INV_SOCIAL_HISTORY_INC', 'S_INV_SYMPTOM', 'S_INV_SYMPTOM_INC',
        'S_INV_TRAVEL', 'S_INV_TRAVEL_INC', 'S_INV_TREATMENT', 'S_INV_TREATMENT_INC',
        'S_INV_UNDER_CONDITION', 'S_INV_UNDER_CONDITION_INC', 'S_INV_VACCINATION', 'S_INV_VACCINATION_INC',
        'S_INVESTIGATION', 'S_INVESTIGATION_REPEAT', 'S_INVESTIGATION_REPEAT_INC', 'S_LDF_DIMENSIONAL_DATA',
        'S_MOVE_CNTRY', 'S_MOVE_CNTY', 'S_MOVE_STATE', 'S_MOVED_WHERE',
        'S_ORGANIZATION', 'S_OUT_OF_CNTRY', 'S_PATIENT', 'S_PCR_SOURCE',
        'S_PLACE', 'S_PROVIDER', 'S_RASH_LOC_GEN', 'S_SMR_EXAM_TY',
        'S_TB_HIV', 'S_TB_PAM', 'S_TB_PAM_ACT_ENTITY', 'S_UPDATED_LAB',
        'S_VACCINATION', 'S_VAR_PAM', 'S_VAR_PAM_ACT_ENTITY', 'SAS_PLACE_UID_COLL',
        'SAS_S_PLACE_POSTALA', 'SAS_S_PLACE_TELE', 'SR100', 'STAGING_KEY_REPT_FINAL',
        'STD_HIV_DATAMART', 'SUMM_DATAMART', 'SUMMARY_CASE_GROUP', 'SUMMARY_REPORT_CASE',
        'TB_DATAMART', 'TB_HIV_DATAMART', 'TB_PAM_LDF', 'TEMP_UPDATED_LAB_INV_MAP',
        'TEST_RESULT_GROUPING', 'TMP_BothTable', 'TMP_CASE_LAB_DATAMART_MODIFIED', 'TREATMENT',
        'TREATMENT_EVENT', 'UPDATED_LAB_TEST_LIST', 'UPDATED_OBSERVATION_LIST', 'USER_PROFILE',
        'VACCINATION_ARCHIVE', 'VAR_DATAMART', 'VAR_PAM_LDF'
    )
    AND t.TABLE_TYPE = 'BASE TABLE'
    AND NOT EXISTS (
        SELECT 1
        FROM RDB.INFORMATION_SCHEMA.COLUMNS col
        WHERE col.TABLE_NAME = t.TABLE_NAME
        AND col.COLUMN_NAME LIKE '%UID%'
    )
GROUP BY t.TABLE_NAME
ORDER BY t.TABLE_NAME;
